### ISSUE TITLE
create GeoFeedWebfingerProfile

### ISSUE THREAD

**Issue by elf-pavlik** [apollo-ng/dspace-app-apollong#11]
**Type:** _pull_
1. takes list of webfinger addresses
2. fetches profiles and gets geolocation directly from them
3. refresh on demand or on interval

**Comment by nilclass** [comment]
@elf-pavlik is there a spec for geolocation links in webfinger profiles?

**Comment by elf-pavlik** [comment]
not that i know of...
we can start with something simple and then keep looking for more standard format...
we could look at vcard rdf for example
http://www.w3.org/Submission/vcard-rdf/#Geo

**Comment by nilclass** [comment]
So that would mean adding a 
`{ "rel":"http://www.w3.org/2006/vcard/ns#", "href":"..."}` link, with the `href` pointing to some vcard in VCF, RDF or JSON-LD?

**Comment by nilclass** [comment]
There is also http://www.w3.org/2003/01/geo/ for locations only

**Comment by nilclass** [comment]
(i.e. http://www.w3.org/2003/01/geo/wgs84_pos# as vocabulary)

**Comment by elf-pavlik** [comment]
too non precise for now, i captured ink to this conversation in: http://pad.hackers4peace.net/p/buddyradar
