### ISSUE TITLE
add icon to "apollo-ng" github organization

### ISSUE THREAD

**Issue by nilclass** [apollo-ng/dspace-app-apollong#12]
To do this someone needs to create an email address, sign up at [gravatar](http://en.gravatar.com/), upload an icon and add that email addr as "gravatar email" in [organization settings](https://github.com/organizations/apollo-ng/settings/profile).

**Comment by elf-pavlik** [comment]
@chron0 already started but got lost in spam filter or sth :D
can you just create gravatar@open-resource.org for that purpose?

**Comment by elf-pavlik** [comment]
i made apollo-ng@wwelves.org for now, later we can switch to something more suited... also image looks bit crappy:
https://secure.gravatar.com/avatar/06d063c8849abf27356e1c2e849b9631?s=420&d=https://a248.e.akamai.net/assets.github.com%2Fimages%2Fgravatars%2Fgravatar-org-420.png

@chron0

**Comment by yggi** [comment]
ok, the icon is there. can this issue be closed?

**Comment by elf-pavlik** [comment]
@yggi  i would prefer if @chron0 sends me nicer version of logo before he gets heart attack seeing my gimp fu :D

**Comment by elf-pavlik** [comment]
made it bit less ugly :)
