### ISSUE TITLE
refactor Overlays

### ISSUE THREAD

**Issue by elf-pavlik** [apollo-ng/dspace-app-apollong#21]
@alice-wl have worked on it on feature/UserOverlay branch!

**Comment by elf-pavlik** [comment]
@alice-wl i think all your work on overlays got merged? do you concur?

**Comment by alice-wl** [comment]
indeed, merged and deleted (hint!:)

**Comment by elf-pavlik** [comment]
@alice-wl i didn't get it... can we close this one?
