### ISSUE TITLE
Client breaks if selected map provider doesn't deliver

### ISSUE THREAD

**Issue by chron0** [apollo-ng/dspace-app-apollong#29]
Uncaught TypeError: Cannot call method 'match' of undefined modestmaps.js:805

leaves a non-working client with no option to change the map provider :)

**Comment by chron0** [comment]
This was strange, even after the tileserver delivered again, client was broken. Only localStorage.clear(); fixed it.

**Comment by elf-pavlik** [comment]
@chron0 i think issue came from some stuff in your local storage, i change tileset template to false string, map deosn't show but client works and i can chenge it...
