### ISSUE TITLE
setup automated testing

### ISSUE THREAD

**Issue by elf-pavlik** [apollo-ng/dspace-app-apollong#3]
so far we work like cowboys ;)

once this one done i'll look at getting us on continuous integration!

**Comment by yggi** [comment]
+1. We considered http://visionmedia.github.com/mocha/ , didn't we?

**Comment by elf-pavlik** [comment]
@yggi yup! for unit testing it will do...

for integration we can test later with: http://metaskills.net/mocha-phantomjs/
or: http://zombie.labnotes.org/
or http://seleniumhq.org/

:+1:

**Comment by elf-pavlik** [comment]
i would like to put info on how to test in README and then we can close it again :)

**Comment by yggi** [comment]
done with 235d92a5ace9197515d6e460771ba613031784f8

**Comment by elf-pavlik** [comment]
improve info about testing in README

**Comment by yggi** [comment]
@elf-pavlik what additional info should go into the README?
