### ISSUE TITLE
create 2 distinc modes for UI - base (desktop) & field (mobile)

### ISSUE THREAD

**Issue by elf-pavlik** [apollo-ng/dspace-app-apollong#35]
i have impression that having one UI and trying to have it functional on desktop and mobile won't get us far... sometimes we want to use a desktop machine to do some editing etc using more comfy UI which utilizes more screen real estate ( **base** mode) then we may want to work from more restricted in space mobile UI ( **field** mode)

**Comment by yggi** [comment]
hmm, personally i would prefer to see the interface as consistent as possible over different devices.

**Comment by elf-pavlik** [comment]
consistent - sure!
exactly the same - no so sure ;)

**Comment by chron0** [comment]
We need to give the ONE UI more "intelligence" to adapt to different conditions, i.e. screen size, orientation and then define different views that automatically take precedence if display space is tight or the orientation doesn't allow a certain view. I'll work an an abstract, which views should be used in which mode. But having two different UI's and their different JS/CSS child deps is not the solution we are looking for.

**Comment by elf-pavlik** [comment]
i didn't say anywhere about different JS/CSS just UI having two modes **field**(mobile) and **base**(desktop)

**Comment by elf-pavlik** [comment]
@nilclass made some relevant changes in 686d5bb

**Comment by nilclass** [comment]
not exactly relevant changes. just cleaned up stuff for the usecase at elevate. just to clarify: I don't think the way it's done is a good solution.

**Comment by elf-pavlik** [comment]
here we made seperate UIs for 2 modes https://github.com/elevate-festival/neokarto-party
for now in same repo but soon i would like to split dspace-api with models and collections and dspace-ui-xxx for view / routing

@nilclass i think of using npm and bower for dspace-api and just bower for various ui variants
later we could look at distribution mechanism to combine api, uis and various server components into various configurable setups :)

**Comment by elf-pavlik** [comment]
moving to #103
