### ISSUE TITLE
"Add Overlay" Button

### ISSUE THREAD

**Issue by yggi** [apollo-ng/dspace-app-apollong#39]
We need the functionality to add an overlay. Something simple at first, that may grow to a full blown directory / repository.

**Comment by chron0** [comment]
AddOverlay tab introduced, needs to open a new modal window now (directory)

**Comment by elf-pavlik** [comment]
@yggi supposedly you have worked on it? we want to rethink and tidy up all the modal/panel setup so nice if we can merge it before doing that!

**Comment by elf-pavlik** [comment]
button present, now we continue on that in #73
