### ISSUE TITLE
Accuracy Icon in statusPanel broken after move to AMD

### ISSUE THREAD

**Issue by chron0** [apollo-ng/dspace-app-apollong#46]
The Acc Icon in the statusPanel doesn't change the color (the class, defining red/yellow or green) anymore. IIRC this happened after the big AMD merge.

**Comment by yggi** [comment]
accuracy is back again, only color is missing to close the issue :)

**Comment by chron0** [comment]
userGeoStatus icons added to sprite - color change working with cdb9ae1
