### ISSUE TITLE
investigate performance issues

### ISSUE THREAD

**Issue by yggi** [apollo-ng/dspace-app-apollong#47]
freenode/#apollo 2013-02-14
21:47 < alice|wl> and dspace emptied my battery
21:48 < alice|wl> too much bg activity
21:53 < chron0> yeah definitely
21:54 < chron0> I can see it even on the desktop, after a night, when the 
                browser was open all night I need to close the tab and reopen 
                the page again to get "normal" performance again
21:55 < chron0> I don't remember who said it, when I was talking about my 
                concerns about performance: "Ah don't worry about that, we can 
                always tune it later..." :)
21:57 < chron0> if this is still true and not something that would require a 
                fundamental change of the codebase I think we really can tune 
                it later :)

**Comment by chron0** [comment]
@nilclass updated some parts of the code including the geofeed where the geoAPI watcher updated the location even it it didn't change. This was done somewhen in the part but got lost on the way. Now it's back and the stress on the browser is minimized a lot. I'll close this for now, but feel free to reopen it at any time, when you're still having issues...
