### ISSUE TITLE
hide minimap should actually hide the minimap, not only move it offscreen

### ISSUE THREAD

**Issue by yggi** [apollo-ng/dspace-app-apollong#48]
the current behavior leads to useless and confusing scrolling of the whole page content on android (and an unknown version of firefox on windows)

**Comment by chron0** [comment]
Yeah, I was thinking the same to fix the "drag the panel and the whole app moves out of the screen" issue.

**Comment by yggi** [comment]
solved with ebd4a06730e48e98118f88d320872ae77006860e
the problem runs deeper though, see #54
