### ISSUE TITLE
fading stuff offscreen is broken on mobile devices

### ISSUE THREAD

**Issue by yggi** [apollo-ng/dspace-app-apollong#54]
using animate() to move stuff offscreen in various fx seems to increase the size of <body> on android, so that useless scrolling gets enabled. 

it is circumvented for the minimap for now (#48), but still happens for the featureBox and the status bars.

**Comment by chron0** [comment]
same is true for non-mobile browser but mouse using tends to never dragging the interface by accident as opposed to touch, so it never bubbled as a bug. I'll see what I can put up as alternative, either the decrease height to 0 animation or just simple fades... whatever works :)

**Comment by chron0** [comment]
merged
