### ISSUE TITLE
Integrate Remote-Storage widget

### ISSUE THREAD

**Issue by chron0** [apollo-ng/dspace-app-apollong#65]
With the introduction of the widgetbar and the former UI cleanup the original remote-storage implementation doesn't work anymore. The current UI offers a widgetbar and widgeticons (one already for remote-storage), where a click should open a submodal with the height of the minimap and provide remote-storage login capability.

**Comment by elf-pavlik** [comment]
@chron0 do you have ui element for such submodal ready?

**Comment by elf-pavlik** [comment]
@nilclass next week in Berlin we could tackle on this one together?

**Comment by chron0** [comment]
widgetBar refactored as widgetBar class in panels.js. The widgetBar gets rendered, but the events wont fire yet to open the modal: https://github.com/chron0/dspace-client/tree/feature/widgetBar. Basic template harnesses are also integrated but should receive their content from the plugin (i.e. remote-storage needs etc.)

**Comment by elf-pavlik** [comment]
while working on #74 i removed remote storage setup from ui.js will post link to related commit after doing interactive rebase! for now message "PRUNE: RemoteStorage setup"

**Comment by chron0** [comment]
done!
