### ISSUE TITLE
setup Push Deploy

### ISSUE THREAD

**Issue by elf-pavlik** [apollo-ng/dspace-app-apollong#7]
we could just have a **demo** remote in git and deploy by simply pushing to it!
to investigate: 
- http://bengourley.co.uk/node-git-deployment-process
- https://github.com/substack/fleet
- more with key _git push deploy_

@alice-wl || @chron0 would you like to pick this one? :)

**Comment by elf-pavlik** [comment]
@chron0 could you self-assign to this one? :)

**Comment by chron0** [comment]
already build, waiting for new build process in Makefile

**Comment by elf-pavlik** [comment]
@chron0 can you still assign this issue to yourself and close it once all deployments work?

**Comment by nilclass** [comment]
@chron0 this should do a successful build:

``` bash
npm install # (in case deps were added)
make build
cp -r build/* /wherever/the/web/root/is/
```

**Comment by chron0** [comment]
alrighty, I will test that and change the post-update hook accordingly

**Comment by yggi** [comment]
push deploy (on 'development' branch) works on http://dspace-develop.open-resource.org/ , thx to @chron0
