### ISSUE TITLE
OverlayManager

### ISSUE THREAD

**Issue by elf-pavlik** [apollo-ng/dspace-app-apollong#73]
following on issue #39 we now can implement a generic UI for managing overlays, sort of a browser which to get started may use data from local storage...

**Comment by yggi** [comment]
I already have a branch with some functionality in that direction, will be a pull request soon. Unfortunatly, sickness prevents me from doing anything usefull at the moment.

**Comment by elf-pavlik** [comment]
@yggi i've almost finished a major refactoring of plumbing in UI, please take a look at it and see if you can easily port your work to work on top of that? https://github.com/elf-pavlik/dspace-client/tree/refactor/panel-modal

**Comment by chron0** [comment]
Done!
