### ISSUE TITLE
build instructions, e.g. INSTALL.md

### ISSUE THREAD

**Issue by guaka** [apollo-ng/dspace-app-apollong#81]
It would be useful to have a basic INSTALL.md with some instructions on how to run this.

Now I get:

```
$ make
-n Building Ender...

module.js:340
    throw err;
          ^
Error: Cannot find module '/Users/guaka/playground/dspace-client/node_modules/.bin/ender'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.runMain (module.js:492:10)
    at process.startup.processNextTick.process._tickCallback (node.js:244:9)
make: *** [ender] Error 1
```

**Comment by guaka** [comment]
after `npm install ender` I get a wee bit further

```
$ make
-n Building Ender...
npm http GET https://registry.npmjs.org/bonzo
npm http GET https://registry.npmjs.org/bean
npm http GET https://registry.npmjs.org/domready
npm http GET https://registry.npmjs.org/qwery
npm http GET https://registry.npmjs.org/morpheus
npm http GET https://registry.npmjs.org/ender-js
npm http 200 https://registry.npmjs.org/domready
npm http GET https://registry.npmjs.org/domready/-/domready-0.2.11.tgz
npm http 200 https://registry.npmjs.org/morpheus
npm http GET https://registry.npmjs.org/morpheus/-/morpheus-0.6.7.tgz
npm http 200 https://registry.npmjs.org/qwery
npm http GET https://registry.npmjs.org/qwery/-/qwery-3.4.1.tgz
npm http 200 https://registry.npmjs.org/ender-js
npm http GET https://registry.npmjs.org/ender-js/-/ender-js-0.4.4-1.tgz
npm http 200 https://registry.npmjs.org/bonzo
npm http GET https://registry.npmjs.org/bonzo/-/bonzo-1.3.4.tgz
npm http 200 https://registry.npmjs.org/bean
npm http GET https://registry.npmjs.org/bean/-/bean-1.0.3.tgz
sed: 1: "ender.js": invalid command code e
make: *** [ender] Error 1
$ make
-n Building Ender...
sed: 1: "ender.js": invalid command code e
make: *** [ender] Error 1
```

**Comment by elf-pavlik** [comment]
@guaka have you followed: https://github.com/apollo-ng/dspace-client#dev ? :)

**Comment by guaka** [comment]
Ah no, cool!

I think this could be a little bit more verbose though.
E.g. add the word "installation" or "install" somewhere :)

And I still get stuck:

```
$ make deps
-n Building Ender...
sed: 1: "ender.js": invalid command code e
make: *** [ender] Error 1
```

**Comment by elf-pavlik** [comment]
@guaka since we work just on client componen, one needs to take all those steps only for development, for simple use @alice-wl works on android wrapper and later we can look at ways to distribute it as packaged web app ping @nilclass 

checking make deps issue now!

**Comment by elf-pavlik** [comment]
@guaka it should work if you just do

```
./run.js
```

and visit localhost as it suggest :)

we should add to README ### run section above ###dev

thanks for feedback!

**Comment by guaka** [comment]
`./run.js` works but localhost:3000 is stuck with this:

![Screen Shot 2013-03-20 at 11 52 35 PM](https://f.cloud.github.com/assets/54728/283491/ec85508a-91b0-11e2-88ae-d93ac8e5b3af.png)

**Comment by elf-pavlik** [comment]
@guaka any errors in browser's console? just ping me on jabber if you like and we can deal with it together!

**Comment by guaka** [comment]
Yep:

Failed to load resource: the server responded with a status of 404 (Not
Found) http://localhost:3000/deps/require.js
 Uncaught ReferenceError: requirejs is not defined

**Comment by realitygaps** [comment]
I have the same error on the develop branch

**Comment by chron0** [comment]
Yeah, my bad. I've been vigorously testing the dev/build process in the past to make sure stuff like that didn't happen, because once you are set up you never issues like that anymore. When we change something in the process then, we mostly wouldn't realize that it was broken, because we already have it set up. I'll start with a naked setup again, to find out why it fails. It is most likely linked to the issue with the demo, since the deploy is broken there as well. Sorry for the delay on feedback and the lack of bare init testing :)

**Comment by chron0** [comment]
@nilclass debugged the build process and fixed some issues, another bare-repo init test was also successfull. Could you guys please try again, and make sure not to use anything above NodeJS 0.8.x? I will close the ticket here when I've moved the stuff into INSTALL.MD :)

**Comment by chron0** [comment]
Ok, Done now. Could you please test again, if it works now when using the Installation walktrough in INSTALL.md? The build has been tested here successfully so it should work for you too. Don't hesitate to ask any question, when you get stuck, so that we can update the docs on parts that are not clear.
