### ISSUE TITLE
setup Documentation autogenerate

### ISSUE THREAD

**Issue by elf-pavlik** [apollo-ng/dspace-app-apollong#9]
at this moment we need to generate gh-pages branch by hand
we may also move it to http://dspace.open-resource.org/client/api

**Comment by nilclass** [comment]
In remoteStorage.js I use a "commit-docs" task to make this less of a hassle: https://github.com/RemoteStorage/remoteStorage.js/blob/master/Makefile#L37

**Comment by elf-pavlik** [comment]
thx for pointer @nilclass :)

@chron0 would you like to pick up this taks as well? :D

**Comment by chron0** [comment]
this should move to the auto-deploy, but I think it would also need to be a part of the build functionality

**Comment by yggi** [comment]
autogenerated documentation (from push deploy) now at http://dspace-develop.open-resource.org/doc/app/files/dspace-js.html
